### ISSUE TITLE
Comment Clarity

### ISSUE THREAD

**Issue by CodyCahoon** [CodyCahoon/ENSO#10]
@bradyrx I just added more comments throughout and wanted to know if they were clear, are saying the correct things, and if we should add more?

**Comment by bradyrx** [comment]
I think the commenting is great overall. It does the job -- I just need to read over everything like 10-15 more times to understand it all. You've officially lost me, simply due to my limited knowledge in this language as of now. But this is something I'll be actively working on this fall, so hopefully I can catch up :P
