### ISSUE TITLE
Scaling of circles

### ISSUE THREAD

**Issue by CodyCahoon** [CodyCahoon/ENSO#6]
Should the circle size be relative to the largest data point (i.e. 0 - 2.36 for nino34) or should it be 0-3?

**Comment by bradyrx** [comment]
I would say to scale the size relative to the largest data point (e.g. 2.36 for nino34), since the -3 to 3 scale is an arbitrary, round-off idea. By scaling to the largest data point, this leaves the vis robust to future el ninos. Perhaps one crops up over 3... although unlikely, it'll adjust automatically to that.

**Comment by CodyCahoon** [comment]
Sounds good. Currently it is relative to the largest data point. Here is the formula we are using:
`.domain([0, nino34.max])` which then maps to:
 `.range([0.5, (height - (2*padding)) / 24]);`

We are setting the initial range value to 0.5 just so we are able to see somewhat circles that are a value around 0
